// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// x_per_indiv_rcpp
NumericMatrix x_per_indiv_rcpp(List x_list, List index_list);
RcppExport SEXP _saemvs_x_per_indiv_rcpp(SEXP x_listSEXP, SEXP index_listSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type x_list(x_listSEXP);
    Rcpp::traits::input_parameter< List >::type index_list(index_listSEXP);
    rcpp_result_gen = Rcpp::wrap(x_per_indiv_rcpp(x_list, index_list));
    return rcpp_result_gen;
END_RCPP
}
// mat_inv
arma::mat mat_inv(const arma::mat& A);
RcppExport SEXP _saemvs_mat_inv(SEXP ASEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type A(ASEXP);
    rcpp_result_gen = Rcpp::wrap(mat_inv(A));
    return rcpp_result_gen;
END_RCPP
}
// solve_linear_syst
arma::mat solve_linear_syst(const arma::mat& A, const arma::mat& B);
RcppExport SEXP _saemvs_solve_linear_syst(SEXP ASEXP, SEXP BSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type A(ASEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type B(BSEXP);
    rcpp_result_gen = Rcpp::wrap(solve_linear_syst(A, B));
    return rcpp_result_gen;
END_RCPP
}
// kronecker_gamma_diag_mult
arma::mat kronecker_gamma_diag_mult(const arma::mat& gamma, const arma::vec& d_diag, int p);
RcppExport SEXP _saemvs_kronecker_gamma_diag_mult(SEXP gammaSEXP, SEXP d_diagSEXP, SEXP pSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type d_diag(d_diagSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    rcpp_result_gen = Rcpp::wrap(kronecker_gamma_diag_mult(gamma, d_diag, p));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_saemvs_x_per_indiv_rcpp", (DL_FUNC) &_saemvs_x_per_indiv_rcpp, 2},
    {"_saemvs_mat_inv", (DL_FUNC) &_saemvs_mat_inv, 1},
    {"_saemvs_solve_linear_syst", (DL_FUNC) &_saemvs_solve_linear_syst, 2},
    {"_saemvs_kronecker_gamma_diag_mult", (DL_FUNC) &_saemvs_kronecker_gamma_diag_mult, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_saemvs(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
